"""add_user_password_hash

Revision ID: cd682c8574c1
Revises: 4e1e63e2bb80
Create Date: 2026-07-07 15:45:11.003641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd682c8574c1'
down_revision: Union[str, None] = '4e1e63e2bb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
