"""description

Revision ID: 4e1e63e2bb80
Revises: 015
Create Date: 2026-07-07 09:53:13.346706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e1e63e2bb80'
down_revision: Union[str, None] = '015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_products_store_sku'), table_name='products')
    op.create_unique_constraint('uq_products_store_sku', 'products', ['store_id', 'sku'])
    op.drop_constraint(op.f('fk_sale_items_sale'), 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.alter_column('store_business_days', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_business_days', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_business_days', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_business_days', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sale_items_sale'), 'sale_items', 'sales', ['sale_id'], ['id'])
    op.drop_constraint('uq_products_store_sku', 'products', type_='unique')
    op.create_index(op.f('uq_products_store_sku'), 'products', ['store_id', 'sku'], unique=True)
    # ### end Alembic commands ###
